# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="CHROMATIC"
MODULE_VERSION="1.20140408"


inherit perl-module

DESCRIPTION="Perl extension for emulating troublesome interfaces"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=perl-gcpan/UNIVERSAL-isa-1.20140927
	>=perl-gcpan/Test-Warn-0.30
	>=perl-gcpan/Test-Exception-0.38
	>=perl-gcpan/UNIVERSAL-can-1.20140328
	dev-lang/perl"
