# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="OLEG"
MODULE_VERSION="0.06"


inherit perl-module

DESCRIPTION="LWP::UserAgent with simple caching mechanism"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=perl-gcpan/Test-Mock-LWP-Dispatch-0.06
	dev-lang/perl"
