# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="ETHER"
MODULE_VERSION="1.20140927"


inherit perl-module

DESCRIPTION="Attempt to recover from people calling UNIVERSAL::isa as a function"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=perl-gcpan/Module-Build-Tiny-0.039
	dev-lang/perl"
