# Copyright 2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.0

EAPI=8

CRATES="
	aho-corasick-0.6.8
	ansi_term-0.11.0
	assert_cli-0.6.3
	atty-0.2.11
	backtrace-0.3.9
	backtrace-sys-0.1.24
	bitflags-1.0.4
	cc-1.0.25
	cfg-if-0.1.5
	clap-2.32.0
	colored-1.6.1
	difference-2.0.0
	environment-0.1.1
	failure-0.1.2
	failure_derive-0.1.2
	itoa-0.4.3
	lazy_static-1.1.0
	libc-0.2.43
	memchr-2.0.2
	percent-encoding-1.0.1
	proc-macro2-0.4.19
	quote-0.6.8
	redox_syscall-0.1.40
	redox_termios-0.1.1
	regex-1.0.5
	regex-syntax-0.6.2
	rustc-demangle-0.1.9
	ryu-0.2.6
	serde-1.0.79
	serde_derive-1.0.79
	serde_json-1.0.27
	strsim-0.7.0
	syn-0.14.9
	syn-0.15.4
	synstructure-0.9.0
	termion-1.5.1
	textwrap-0.10.0
	thread_local-0.3.6
	toml-0.4.6
	ucd-util-0.1.1
	unicode-width-0.1.5
	unicode-xid-0.1.0
	utf8-ranges-1.0.1
	vec_map-0.8.1
	version_check-0.1.4
	winapi-0.3.5
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

MY_PN="cargo-readme"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="A cargo subcommand to generate README.md content from doc comments"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/livioribeiro/cargo-readme"
SRC_URI="https://github.com/livioribeiro/cargo-readme/archive/v${PV}.tar.gz -> ${P}.tar.gz $(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 Boost-1.0 MIT MPL-2.0 Unlicense"
SLOT="0"
KEYWORDS="~amd64"

S="${WORKDIR}/${MY_P}"
