# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=7

CRATES="
adler-0.2.3
adler32-1.2.0
aho-corasick-0.7.15
ansi_term-0.11.0
ansi_term-0.12.1
atty-0.2.14
autocfg-1.0.1
bitflags-1.2.1
byteorder-1.3.4
cargo_metadata-0.12.0
cc-1.0.61
cfg-if-0.1.10
cfg-if-1.0.0
chrono-0.4.19
clap-2.33.3
coveralls-api-0.5.0
crc32fast-1.2.1
curl-0.4.34
curl-sys-0.4.38+curl-7.73.0
deflate-0.8.6
fallible-iterator-0.2.0
flate2-1.0.19
generator-0.6.23
gimli-0.22.0
git2-0.13.12
gzip-header-0.3.0
hashbrown-0.9.1
hermit-abi-0.1.17
hex-0.4.2
humantime-2.0.1
humantime-serde-1.0.1
idna-0.2.0
indexmap-1.6.0
itoa-0.4.6
jobserver-0.1.21
lazy_static-1.4.0
libc-0.2.80
libflate-1.0.3
libflate_lz77-1.0.0
libgit2-sys-0.12.14+1.1.0
libssh2-sys-0.2.19
libz-sys-1.1.2
log-0.4.11
loom-0.3.6
matchers-0.0.1
matches-0.1.8
md5-0.7.0
memchr-2.3.4
memmap-0.7.0
miniz_oxide-0.4.3
nix-0.19.0
num-integer-0.1.44
num-traits-0.2.14
object-0.22.0
openssl-probe-0.1.2
openssl-sys-0.9.58
percent-encoding-2.1.0
pest-2.1.3
pin-project-lite-0.1.11
pkg-config-0.3.19
proc-macro2-1.0.24
procfs-0.8.1
quick-xml-0.20.0
quote-1.0.7
redox_syscall-0.1.57
regex-1.4.2
regex-automata-0.1.9
regex-syntax-0.6.21
rle-decode-fast-1.0.1
rustc-demangle-0.1.18
rustc_version-0.2.3
rustc_version-0.3.0
ryu-1.0.5
same-file-1.0.6
schannel-0.1.19
scoped-tls-1.0.0
semver-0.11.0
semver-0.9.0
semver-parser-0.10.1
semver-parser-0.7.0
serde-1.0.117
serde_derive-1.0.117
serde_json-1.0.59
sharded-slab-0.1.0
smallvec-1.4.2
socket2-0.3.15
stable_deref_trait-1.2.0
strsim-0.8.0
syn-1.0.48
textwrap-0.11.0
thread_local-1.0.1
time-0.1.44
tinyvec-0.3.4
toml-0.5.7
tracing-0.1.21
tracing-attributes-0.1.11
tracing-core-0.1.17
tracing-log-0.1.1
tracing-subscriber-0.2.15
ucd-trie-0.1.3
unicode-bidi-0.3.4
unicode-normalization-0.1.13
unicode-width-0.1.8
unicode-xid-0.2.1
url-2.1.1
vcpkg-0.2.10
vec_map-0.8.2
walkdir-2.3.1
wasi-0.10.0+wasi-snapshot-preview1
wasmparser-0.57.0
winapi-0.3.9
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.5
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Cargo-Tarpaulin is a tool to determine code coverage achieved via tests"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/xd009642/tarpaulin"
SRC_URI="https://github.com/xd009642/tarpaulin/archive/${PV}.tar.gz -> ${P}.tar.gz $(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="BSD Apache-2.0 Apache-2.0 WITH LLVM-exception BSL-1.0 MIT Unlicense Zlib"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
