#!/sbin/openrc-run
# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

run_dir=${run_dir:-/run/}
command="/usr/bin/rdm"
command_background="true"
pidfile=${run_dir}/${SVCNAME}.pid
socket=$(getent passwd ${user} | cut -d: -f6 )/.${SVCNAME}
command_args="--socket-file ${socket}"
user=${user:-rdm}
group=${group:-rdm}
start_stop_daemon_args="--user ${user} --group ${group} --background \
	--make-pidfile --stdout ${logfile} --stderr ${logfile} \
	--ionice ${ionice} --nicelevel ${nicelevel}
	--pidfile ${pidfile}"
start_stop_daemon_stop_args="-R TERM/3/KILL/5"

depend() {
	use net
}

start_pre() {
    checkpath -f "${logfile}" -o "${user}:${group}"
    checkpath -f "${logfile}" -o "${user}:${group}"
}
