# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="CHORNY"
MODULE_VERSION="0.30"


inherit perl-module

DESCRIPTION="Perl extension to test methods for warnings"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=perl-gcpan/Sub-Uplevel-0.25
	dev-lang/perl"
